version: 2.1
workflows:
  main:
    jobs:
      - build
jobs:
  build:
    machine:
      image: ubuntu-2204:2022.04.2
    resource_class: large

    steps:
      - checkout

      # - run: 
      #     name: Install requirements
      #     command: pip install -r requirements.txt

      # - run: 
      #   name: Install requirements
      #   command: pip install -r requirements.txt

      # - run: 
      #     name: Install requirements
      #     command: pip install -r requirements.txt

      # - run: 
      #   name: Install requirements
      #   command: pip install -r requirements.txt

      - run: echo "Do some things"
      - run: python3 --version