version: 2.1
workflows:
  main:
    jobs:
      - build
jobs:
  build:
    machine:
      image: ubuntu-2204:2022.04.2
    resource_class: large

    steps:
      - checkout

      - run: 
          name: Install Libs
          command: sudo sh libs_installation.sh


      # - run: 
      #     name: Install requirements
      #     command: sudo pip3 install -r requirements.txt

      # - run: 
      #     name: Start Script
      #     command: sudo python3 /home/circleci/project/start_script.py --slot=day --acc=A

      # - run: 
      #   name: Install requirements
      #   command: pip install -r requirements.txt

      # - store_artifacts:
      #     path: ss
      #     destination: artifact-file

